### ISSUE TITLE
 line 236, in async_setup yield from hass.data[setup_domain].async_add_entities(entities) KeyError: 'input_select'

### ISSUE THREAD

**Issue by kukudemajia** [cnk700i/common_timer#1]
Home Assistant
0.83.3

按照默认配置，运行后有出错提示

Error during setup of component common_timer
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/home/homeassistant/.homeassistant/custom_components/common_timer/__init__.py", line 236, in async_setup
    yield from hass.data[setup_domain].async_add_entities(entities)
KeyError: 'input_select'

setup_domain:input_select,entities:[<Entity 设备类型: ---请选择设备类型--->, <Entity 设备名称: ---请选择设备--->, <Entity 操作: 关>]

**Comment by cnk700i** [comment]
看教程，还有三个组件要修改的
